tunnel: 1e645547-fc54-41b3-ba38-335def20b90a # Replace <TUNNEL_ID> with your actual tunnel ID
credentials-file: /etc/cloudflared/1e645547-fc54-41b3-ba38-335def20b90a.json # This path should match the path where your credentials file is located

ingress:
  - hostname: "web.wania.xyz"
    service: "http://backend:8001"
  - service: "http_status:404"
